## 06 ``numpy.array`` 合并和分割

In [20]:
import numpy as np

### ``numpy.array`` 的合并

In [21]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [22]:
x.ndim

1

In [23]:
y.ndim

1

In [24]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [25]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [28]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [30]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [35]:
np.concatenate([A, z.reshape(-1, 3)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [36]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [37]:
B = np.full((2,2), 100)

In [38]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [41]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### ``numpy.array`` 的分割

In [42]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x1, x2, x3 = np.split(x, [3, 7])

In [45]:
x1

array([0, 1, 2])

In [46]:
x2

array([3, 4, 5, 6])

In [47]:
x3

array([7, 8, 9])

In [48]:
x1, x2 = np.split(x, [5])

In [49]:
x1

array([0, 1, 2, 3, 4])

In [50]:
x2

array([5, 6, 7, 8, 9])

In [51]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
A1, A2 = np.split(A, [2])

In [53]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [54]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
A1, A2 = np.split(A, [2], axis=1)

In [56]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [57]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [58]:
upper, lower = np.vsplit(A, [2])

In [59]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
left, right = np.hsplit(A, [2])

In [62]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [63]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [64]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
X, y = np.hsplit(data, [-1])

In [66]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [67]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [68]:
y[:, 0]

array([ 3,  7, 11, 15])

In [69]:
y.reshape((1, -1))

array([[ 3,  7, 11, 15]])