## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
np.argmin(x)

974167

In [4]:
x[886266]

0.38669695303701057

In [5]:
np.min(x)

-5.078031857055521

In [6]:
np.argmax(x)

442541

In [7]:
x[4851]

0.097766478011801605

In [8]:
np.max(x)

4.583953570368565

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)
x

array([ 7,  3,  1,  4, 10,  6,  5, 11, 14,  2,  8, 15, 13,  9,  0, 12])

In [11]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 7,  3,  1,  4, 10,  6,  5, 11, 14,  2,  8, 15, 13,  9,  0, 12])

In [13]:
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 1, 2, 4],
       [8, 3, 5, 1],
       [3, 1, 2, 1],
       [8, 7, 0, 2]])

In [16]:
np.sort(X, axis=1)

array([[1, 2, 4, 8],
       [1, 3, 5, 8],
       [1, 1, 2, 3],
       [0, 2, 7, 8]])

In [18]:
np.sort(X, axis=0)

array([[3, 1, 0, 1],
       [8, 1, 2, 1],
       [8, 3, 2, 2],
       [8, 7, 5, 4]])

#### 使用索引

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
np.random.shuffle(x)

In [46]:
x

array([14, 15,  8,  7, 10,  4,  9,  1,  6,  5,  3, 12,  2, 11,  0, 13])

In [47]:
np.argsort(x)

array([14,  7, 12, 10,  5,  9,  8,  3,  2,  6,  4, 13, 11, 15,  0,  1])

In [48]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  7,  8,  6,  9, 10, 12, 11, 13, 15, 14])

In [49]:
np.argpartition(x, 3)

array([ 7, 14, 12, 10,  5,  9,  3,  2,  8,  6,  4, 11, 13, 15,  1,  0])

In [50]:
X

array([[8, 8, 5, 8],
       [1, 2, 2, 4],
       [5, 5, 9, 9],
       [3, 9, 3, 4]])

In [51]:
np.argsort(X, axis=1)

array([[2, 0, 1, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 2, 3, 1]])

In [52]:
np.argpartition(X, 2, axis=1)

array([[2, 1, 0, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 2, 3, 1]])